const TEACHER = [
    {
        id: 1,
        username: 'NatBowie',
        password: 'hashedPassword***',
        firstName: 'Natasha',
        lastName: 'Bowie',
        Age: 29,
        Sex: 'Female',
        Nationality: 'UK',
        Race: 'Asian',
        NativeSpeaker: 'yes',
        married: 'no',
        highestDegree: 'BA',
        feildOfDegree: 'English',
        school: 'Florida State University',
        certification: 'none',
        yearsOfTeachingExperience: 1,
        yearsInChina: 0,
        yearsTeachingAbroad: 1,
    },
    {
        id: 2,
        username: 'Kahmed',
        password: 'hashedPassword***',
        firstName: 'Ahmed',
        lastName: 'Kahreem',
        Age: 33,
        Sex: 'Male',
        Nationality: 'USA',
        Race: 'Other',
        NativeSpeaker: 'yes',
        married: 'yes',
        highestDegree: 'AA',
        feildOfDegree: 'General Studies',
        school: 'University of Alabama',
        certification: 'TESL',
        yearsOfTeachingExperience: 2,
        yearsInChina: 1,
        yearsTeachingAbroad: 1,
    }
]

module.exports = TEACHER